import { Task, Member } from '../types/task';
import { Project } from '../types/project';
import { User } from '../types/user';

export const INITIAL_USER: User = {
  id: 'user-1',
  name: 'Dexter',
  email: 'dexter@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  title: 'Designer',
  username: 'Dexuser',
  userType: 'guest',
  isAuthenticated: true,
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'm-1',
    name: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    role: 'Admin',
  },
  {
    id: 'm-2',
    name: 'QA Team',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    role: 'QA Engineer',
  },
  {
    id: 'm-3',
    name: 'Designer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    role: 'Product Designer',
  },
  {
    id: 'm-4',
    name: 'Security',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    role: 'Security Lead',
  },
  {
    id: 'm-5',
    name: 'CN',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    role: 'Developer',
  },
  {
    id: 'm-6',
    name: 'Abhay',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
    role: 'Fullstack Dev',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Design Homepage',
    description: 'Redesign main landing page and high converting call to actions.',
    priority: 'High',
    leadId: 'm-2',
    dueDate: '2026-09-12',
    status: 'Active',
    taskCount: 3,
  },
  {
    id: 'proj-2',
    name: 'Develop Login Feature',
    description: 'Frontend authentication and workspace guest entry flows.',
    priority: 'Low',
    leadId: 'm-5',
    dueDate: '2026-09-15',
    status: 'Active',
    taskCount: 2,
  },
  {
    id: 'proj-3',
    name: 'Test Payment Gateway',
    description: 'Integrate payment provider sandbox and test checkout webhooks.',
    priority: 'Medium',
    leadId: 'm-6',
    dueDate: '2026-09-18',
    status: 'Active',
    taskCount: 2,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Write API Documentation',
    description: 'Create clear and detailed API documentation to guide developers in using the inventory and sales metrics features effectively.',
    status: 'To Do',
    priority: 'High',
    memberIds: ['m-1', 'm-3'],
    labels: ['Research', 'Design', 'Development', 'Testing', 'Deployment'],
    startDate: '2026-07-20',
    dueDate: '2026-07-31',
    projectId: 'proj-1',
    reporterId: 'm-1',
    subtasks: [
      {
        id: 'sub-1',
        title: 'Subtask 1',
        completed: false,
        priority: 'High',
        memberId: 'm-2',
        dueDate: '2026-09-12',
      },
      {
        id: 'sub-2',
        title: 'Subtask 2',
        completed: false,
        priority: 'Low',
        memberId: 'm-5',
        dueDate: '2026-09-15',
      },
      {
        id: 'sub-3',
        title: 'Subtask 3',
        completed: true,
        priority: 'Medium',
        memberId: 'm-6',
        dueDate: '2026-09-18',
      },
    ],
    resources: [
      { id: 'res-1', title: 'API Specification Draft', url: 'https://swagger.io' },
      { id: 'res-2', title: 'Figma System Specs', url: 'https://figma.com' },
    ],
    comments: [
      {
        id: 'c-1',
        authorName: 'Ankit Dutta',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
        content: 'dsds',
        createdAt: 'just now',
      },
    ],
    updates: [
      {
        id: 'u-1',
        authorName: 'You',
        text: 'changed priority from No priority to Urgent',
        createdAt: 'Aug 2026',
      },
      {
        id: 'u-2',
        authorName: 'You',
        text: 'posted an update',
        createdAt: 'Aug 2026',
      },
    ],
  },
  {
    id: 'task-2',
    title: 'Code Review Completed',
    description: 'Comprehensive code review for auth flow and workspace routing.',
    status: 'Doing',
    priority: 'Medium',
    memberIds: ['m-1'],
    labels: ['Deployment', 'Review'],
    dueDate: '2026-07-29',
    projectId: 'proj-2',
    reporterId: 'm-1',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-3',
    title: 'Implement Search Function',
    description: 'Add real time title filtering across task management board and list views.',
    status: 'To Do',
    priority: 'Medium',
    memberIds: ['m-1'],
    labels: ['Deployment', 'Review'],
    dueDate: '2026-07-29',
    projectId: 'proj-1',
    reporterId: 'm-1',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-4',
    title: 'Design Mockups Finalized',
    description: 'Finalize UI assets and high fidelity prototypes in Figma.',
    status: 'Doing',
    priority: 'High',
    memberIds: ['m-1'],
    labels: ['Deployment', 'Review'],
    dueDate: '2026-07-29',
    projectId: 'proj-1',
    reporterId: 'm-3',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-5',
    title: 'Deploy to Production',
    description: 'Prepare production bundle and verify environment variables.',
    status: 'To Do',
    priority: 'Urgent',
    memberIds: ['m-1'],
    labels: ['Deployment', 'Review'],
    dueDate: '2026-07-29',
    projectId: 'proj-2',
    reporterId: 'm-1',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-6',
    title: 'Feature Testing Passed',
    description: 'End-to-end user journey tests completed for tasks and board view.',
    status: 'Completed',
    priority: 'High',
    memberIds: ['m-2'],
    labels: ['Testing', 'Passed'],
    dueDate: '2026-07-30',
    projectId: 'proj-3',
    reporterId: 'm-2',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-7',
    title: 'UI Design Updated',
    description: 'Polished component spacing, theme badges and dropdown menus.',
    status: 'Completed',
    priority: 'High',
    memberIds: ['m-3'],
    labels: ['Design', 'Updated'],
    dueDate: '2026-07-31',
    projectId: 'proj-1',
    reporterId: 'm-3',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-8',
    title: 'Security Audit Scheduled',
    description: 'Vulnerability assessment and session security check.',
    status: 'Completed',
    priority: 'High',
    memberIds: ['m-4'],
    labels: ['Audit', 'Scheduled'],
    dueDate: '2026-08-01',
    projectId: 'proj-3',
    reporterId: 'm-4',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-9',
    title: 'Design Homepage',
    description: 'Main homepage design and layout implementation.',
    status: 'To Do',
    priority: 'High',
    memberIds: ['m-2'],
    labels: ['Design', 'UI'],
    dueDate: '2026-09-12',
    projectId: 'proj-1',
    reporterId: 'm-2',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-10',
    title: 'Develop Login Feature',
    description: 'Guest entry and simulated Google OAuth integration.',
    status: 'To Do',
    priority: 'Low',
    memberIds: ['m-5'],
    labels: ['Auth', 'Frontend'],
    dueDate: '2026-09-15',
    projectId: 'proj-2',
    reporterId: 'm-5',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
  {
    id: 'task-11',
    title: 'Test Payment Gateway',
    description: 'Verify payment modal and checkout response states.',
    status: 'To Do',
    priority: 'Medium',
    memberIds: ['m-6'],
    labels: ['Testing', 'Payments'],
    dueDate: '2026-09-18',
    projectId: 'proj-3',
    reporterId: 'm-6',
    subtasks: [],
    resources: [],
    comments: [],
    updates: [],
  },
];
