services:
  - type: web
    name: ablespace-backend-tpjw
    env: node
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://pyrami.netlify.app
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 7d
